// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDASyzuNGxpx0tqPEkBK7rW8xDXMigvvpI',
    appId: '1:971092063434:web:5906dfb57df3600a8cf033',
    messagingSenderId: '971092063434',
    projectId: 'pressenceapps',
    authDomain: 'pressenceapps.firebaseapp.com',
    storageBucket: 'pressenceapps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHT2TMRTz9Kd5bnGnU_whQx4_-bhr-1rM',
    appId: '1:971092063434:android:f02869dbc55012e58cf033',
    messagingSenderId: '971092063434',
    projectId: 'pressenceapps',
    storageBucket: 'pressenceapps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKJo0CqiTE0xaLW6_ODFPxGTQcwOKpv2Q',
    appId: '1:971092063434:ios:a789515a6664336c8cf033',
    messagingSenderId: '971092063434',
    projectId: 'pressenceapps',
    storageBucket: 'pressenceapps.appspot.com',
    androidClientId: '971092063434-fo8j264r5htuk8ptdkg1k3bkoqif99h8.apps.googleusercontent.com',
    iosClientId: '971092063434-loje5mqjejalkfgo8pna2en6004d5gvg.apps.googleusercontent.com',
    iosBundleId: 'com.sayurcode.pressenceAppsGeolocator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKJo0CqiTE0xaLW6_ODFPxGTQcwOKpv2Q',
    appId: '1:971092063434:ios:a789515a6664336c8cf033',
    messagingSenderId: '971092063434',
    projectId: 'pressenceapps',
    storageBucket: 'pressenceapps.appspot.com',
    androidClientId: '971092063434-fo8j264r5htuk8ptdkg1k3bkoqif99h8.apps.googleusercontent.com',
    iosClientId: '971092063434-loje5mqjejalkfgo8pna2en6004d5gvg.apps.googleusercontent.com',
    iosBundleId: 'com.sayurcode.pressenceAppsGeolocator',
  );
}
